#!/usr/bin/env python

Import('env')

module_env = env.Clone()
src_list = ["spatialos.cpp", "register_types.cpp"]
module_env.Append(CXXFLAGS=['-O2', '-std=c++11'])
module_env.Append(CPPPATH="worker_sdk/cpp/include")
module_env.add_source_files(env.modules_sources, src_list)

worker_sdk_dir = "worker_sdk/";

#lib = env.add_library("spatialos", thirdparty_sources)

afiles = [
    "cpp/lib/libCoreSdk.a",
    "cpp/lib/libgpr.a",
    "cpp/lib/libgrpc.a",
    "cpp/lib/libgrpc++.a",
    "cpp/lib/libprotobuf.a",
    "cpp/lib/libRakNetLibStatic.a",
    "cpp/lib/libssl.a",
    "cpp/lib/libWorkerSdk.a",
    "cpp/lib/libz.a",
]

apaths = [env.File(worker_sdk_dir + file) for file in afiles]

env.Append(LIBPATH=[worker_sdk_dir + "cpp/lib"])
env.Append(LIBS=apaths)
#lib = env.add_library("spatialos", apaths)
#env.Append(LIBS=[lib])
#env.Append(CPPPATH="worker_sdk/cpp/include")

Export('env')